#### Merge in Pandas is used to combine two or more DataFrames based on a common column or key, similar to SQL joins.

In [3]:
import pandas as pd 
df1 =pd.DataFrame({
    'city':['new york','chicago','rolando'],
    'temperature':[21,14,35]
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   rolando           35

In [4]:
df2 = pd.DataFrame({
    'city':['new york','chicago','rolando'],
    'humidity':[65,68,75]
})
df2

       city  humidity
0  new york        65
1   chicago        68
2   rolando        75

In [5]:
df3 = pd.merge(df1,df2,on='city')
df3

       city  temperature  humidity
0  new york           21        65
1   chicago           14        68
2   rolando           35        75

In [7]:
df1 =pd.DataFrame({
    'city':['new york','chicago','rolando' , 'baltimore'],
    'temperature':[21,14,35,32]
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    rolando           35
3  baltimore           32

In [8]:
df2 = pd.DataFrame({
    'city':['new york','chicago','san francisco'],
    'humidity':[65,68,71]
})
df2

            city  humidity
0       new york        65
1        chicago        68
2  san francisco        71

In [15]:
df3=pd.merge(df1,df2,on='city')
df3

       city  temperature  humidity
0  new york           21        65
1   chicago           14        68

In [ ]:
# outer join
df3=pd.merge(df1,df2,on='city' , how='outer')
df3

            city  temperature  humidity
0      baltimore         32.0       NaN
1        chicago         14.0      68.0
2       new york         21.0      65.0
3        rolando         35.0       NaN
4  san francisco          NaN      71.0

In [13]:
# how is inner join
df3 = pd.merge(df1,df2,on='city' , how='inner')
df3

       city  temperature  humidity
0  new york           21        65
1   chicago           14        68

In [ ]:
# Left join
df3 = pd.merge(df1,df2,on='city' , how='left')
df3

        city  temperature  humidity
0   new york           21      65.0
1    chicago           14      68.0
2    rolando           35       NaN
3  baltimore           32       NaN

In [19]:
# Right join
df3 = pd.merge(df1,df2,on='city' , how='right')
df3

            city  temperature  humidity
0       new york         21.0        65
1        chicago         14.0        68
2  san francisco          NaN        71

In [ ]:
# indicater 
df3 = pd.merge(df1,df2,on='city' ,how='outer',indicator=True)
df3

            city  temperature  humidity      _merge
0      baltimore         32.0       NaN   left_only
1        chicago         14.0      68.0        both
2       new york         21.0      65.0        both
3        rolando         35.0       NaN   left_only
4  san francisco          NaN      71.0  right_only

In [25]:
# suffixes 
df1 = pd.DataFrame({
    'city': ['new york','chicago','orlando','baltimore'],
    'tempurature':[21,14,35,38],
    'humidity':[65,68,71,75]
})
df1

        city  tempurature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [27]:
df2 = pd.DataFrame({
    'city':['chicago','new york','san diego'],
    'temperature':[21,14,35],
    'humidity':[65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [30]:
df3 = pd.merge(df1,df2,on='city' ,suffixes=('_left','_right'))
df3

       city  tempurature  humidity_left  temperature  humidity_right
0  new york           21             65           14              68
1   chicago           14             68           21              65