In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('weather_data.csv',parse_dates=['day'])
df

         day  temperature  windspeed    event
0 2017-01-01         32.0         6.0    Rain
1 2017-01-04          NaN         9.0   Sunny
2 2017-01-05         28.0         NaN   Snow
3 2017-01-06          NaN         7.0     NaN
4 2017-01-07         32.0         NaN    Rain
5 2017-01-08          NaN         NaN   Sunny
6 2017-01-09          NaN         NaN     NaN
7 2017-01-10         34.0         8.0  Cloudy
8 2017-01-11         40.0        12.0   Sunny

In [9]:
df.set_index('day' , inplace=True)

In [6]:
df.isnull().sum()

day            0
temperature    4
windspeed      4
event          2
dtype: int64

In [ ]:
# fillna method very powerfull all empty cell fill within second 
df.fillna(0)

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04          0.0         9.0   Sunny
2017-01-05         28.0         0.0   Snow
2017-01-06          0.0         7.0       0
2017-01-07         32.0         0.0    Rain
2017-01-08          0.0         0.0   Sunny
2017-01-09          0.0         0.0       0
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny

In [18]:
# we use distionary to fill empty cell
df.fillna({
    'temperature':0,
    'windspeed ':0,
    'event': 'no event'
})

            temperature  windspeed      event
day
2017-01-01         32.0         6.0      Rain
2017-01-04          0.0         9.0     Sunny
2017-01-05         28.0         0.0     Snow
2017-01-06          0.0         7.0  no event
2017-01-07         32.0         0.0      Rain
2017-01-08          0.0         0.0     Sunny
2017-01-09          0.0         0.0  no event
2017-01-10         34.0         8.0    Cloudy
2017-01-11         40.0        12.0     Sunny

In [19]:
# we use fillna metho ffill . first down fill empty cell
df.fillna(method='ffill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_14416\1055485288.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04         32.0         9.0   Sunny
2017-01-05         28.0         9.0   Snow
2017-01-06         28.0         7.0   Snow
2017-01-07         32.0         7.0    Rain
2017-01-08         32.0         7.0   Sunny
2017-01-09         32.0         7.0   Sunny
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny

In [20]:
# we use fillna method bfill down to up method
df.fillna(method='bfill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_14416\2060582127.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04         28.0         9.0   Sunny
2017-01-05         28.0         7.0   Snow
2017-01-06         32.0         7.0    Rain
2017-01-07         32.0         8.0    Rain
2017-01-08         34.0         8.0   Sunny
2017-01-09         34.0         8.0  Cloudy
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny