In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('weather_data.csv',parse_dates=['day'])
df

         day  temperature  windspeed    event
0 2017-01-01         32.0         6.0    Rain
1 2017-01-04          NaN         9.0   Sunny
2 2017-01-05         28.0         NaN   Snow
3 2017-01-06          NaN         7.0     NaN
4 2017-01-07         32.0         NaN    Rain
5 2017-01-08          NaN         NaN   Sunny
6 2017-01-09          NaN         NaN     NaN
7 2017-01-10         34.0         8.0  Cloudy
8 2017-01-11         40.0        12.0   Sunny

In [3]:
df.set_index('day' , inplace=True)

In [4]:
df.isnull().sum()

temperature    4
windspeed      4
event          2
dtype: int64

In [5]:
# fillna method very powerfull all empty cell fill within second 
df.fillna(0)

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04          0.0         9.0   Sunny
2017-01-05         28.0         0.0   Snow
2017-01-06          0.0         7.0       0
2017-01-07         32.0         0.0    Rain
2017-01-08          0.0         0.0   Sunny
2017-01-09          0.0         0.0       0
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny

In [6]:
# we use distionary to fill empty cell
df.fillna({
    'temperature':0,
    'windspeed ':0,
    'event': 'no event'
})

            temperature  windspeed      event
day
2017-01-01         32.0         6.0      Rain
2017-01-04          0.0         9.0     Sunny
2017-01-05         28.0         0.0     Snow
2017-01-06          0.0         7.0  no event
2017-01-07         32.0         0.0      Rain
2017-01-08          0.0         0.0     Sunny
2017-01-09          0.0         0.0  no event
2017-01-10         34.0         8.0    Cloudy
2017-01-11         40.0        12.0     Sunny

In [7]:
# we use fillna metho ffill . first down fill empty cell
df.fillna(method='ffill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_3756\1055485288.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04         32.0         9.0   Sunny
2017-01-05         28.0         9.0   Snow
2017-01-06         28.0         7.0   Snow
2017-01-07         32.0         7.0    Rain
2017-01-08         32.0         7.0   Sunny
2017-01-09         32.0         7.0   Sunny
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny

In [8]:
# we use fillna method bfill down to up method
df.fillna(method='bfill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_3756\2060582127.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04         28.0         9.0   Sunny
2017-01-05         28.0         7.0   Snow
2017-01-06         32.0         7.0    Rain
2017-01-07         32.0         8.0    Rain
2017-01-08         34.0         8.0   Sunny
2017-01-09         34.0         8.0  Cloudy
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny

In [9]:
df.fillna (method='bfill' ,axis='columns')

C:\Users\Admin\AppData\Local\Temp\ipykernel_3756\1244024137.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna (method='bfill' ,axis='columns')
C:\Users\Admin\AppData\Local\Temp\ipykernel_3756\1244024137.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna (method='bfill' ,axis='columns')

           temperature windspeed    event
day
2017-01-01        32.0        6.0    Rain
2017-01-04         9.0        9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0        7.0     NaN
2017-01-07        32.0       Rain    Rain
2017-01-08       Sunny      Sunny   Sunny
2017-01-09         NaN        NaN     NaN
2017-01-10        34.0        8.0  Cloudy
2017-01-11        40.0       12.0   Sunny

In [11]:
df

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04          NaN         9.0   Sunny
2017-01-05         28.0         NaN   Snow
2017-01-06          NaN         7.0     NaN
2017-01-07         32.0         NaN    Rain
2017-01-08          NaN         NaN   Sunny
2017-01-09          NaN         NaN     NaN
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny

In [10]:
# limit are used for don't show duplicate value when we fill empty cell
df.fillna(method='ffill',limit=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_3756\4229122214.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',limit=1)

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04         32.0         9.0   Sunny
2017-01-05         28.0         9.0   Snow
2017-01-06         28.0         7.0   Snow
2017-01-07         32.0         7.0    Rain
2017-01-08         32.0         NaN   Sunny
2017-01-09          NaN         NaN   Sunny
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny

In [12]:
# interpolate is automic ajust value and fill the empty cell

df.interpolate()

C:\Users\Admin\AppData\Local\Temp\ipykernel_3756\2303643668.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

            temperature  windspeed    event
day
2017-01-01    32.000000        6.00    Rain
2017-01-04    30.000000        9.00   Sunny
2017-01-05    28.000000        8.00   Snow
2017-01-06    30.000000        7.00     NaN
2017-01-07    32.000000        7.25    Rain
2017-01-08    32.666667        7.50   Sunny
2017-01-09    33.333333        7.75     NaN
2017-01-10    34.000000        8.00  Cloudy
2017-01-11    40.000000       12.00   Sunny

In [14]:
# we use time method interpolate for adjusting time based

df.interpolate(method='time')

C:\Users\Admin\AppData\Local\Temp\ipykernel_3756\3588234163.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='time')

            temperature  windspeed    event
day
2017-01-01    32.000000        6.00    Rain
2017-01-04    29.000000        9.00   Sunny
2017-01-05    28.000000        8.00   Snow
2017-01-06    30.000000        7.00     NaN
2017-01-07    32.000000        7.25    Rain
2017-01-08    32.666667        7.50   Sunny
2017-01-09    33.333333        7.75     NaN
2017-01-10    34.000000        8.00  Cloudy
2017-01-11    40.000000       12.00   Sunny

In [15]:
# dropna skip the empty cell and olny show the filled cell
df.dropna()

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny

In [19]:
df.dropna(how='all')

            temperature  windspeed    event
day
2017-01-01         32.0         6.0    Rain
2017-01-04          NaN         9.0   Sunny
2017-01-05         28.0         NaN   Snow
2017-01-06          NaN         7.0     NaN
2017-01-07         32.0         NaN    Rain
2017-01-08          NaN         NaN   Sunny
2017-01-10         34.0         8.0  Cloudy
2017-01-11         40.0        12.0   Sunny