### First import the library

In [17]:
import pandas as pd
import numpy as nb

In [18]:
# Read CSV file 
df = pd.read_csv('stock_market_data.csv')
df.head(2)

  stock data Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4
0    tickers        eps    revenue      price      people
1      GOOGL      27.82         87        845  larry page

In [19]:
# for applying skip header  
df = pd.read_csv('stock_market_data.csv',skiprows=1)
df.head(3)

  tickers    eps  revenue price      people
0   GOOGL  27.82       87   845  larry page
1     MWT   4.61      484    65        n.a.
2    MSFT     -1       85    64   billgates

In [ ]:
# for applying remove the header 
df =pd.read_csv('stock_market_data.csv', header = 1)
df.head(2)

  tickers    eps  revenue price      people
0   GOOGL  27.82       87   845  larry page
1     MWT   4.61      484    65        n.a.

In [ ]:
# if we remove header so we write Header = none and
# give them names use argument name
df=pd.read_csv('stock_market_data.csv',header=None , names=['col_a','col_b','col_c','col_d','col_e'] )
df

        col_a          col_b    col_c  col_d          col_e
0  stock data            NaN      NaN    NaN            NaN
1     tickers            eps  revenue  price         people
2       GOOGL          27.82       87    845     larry page
3         MWT           4.61      484     65           n.a.
4        MSFT             -1       85     64      billgates
5         RJL  not available       50   1023  mukesh ambani
6        TATA            5.6       -1   n.a.     ratan tata

In [ ]:
# we are going orginal data and limit row we so we write nrows 
df = pd.read_csv('stock_market_data.csv',header=1,nrows=3)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     MWT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64   billgates

#### Now we use na_value for empty cell

In [27]:
df = pd.read_csv('stock_market_data.csv', header=1 , na_values=[-1,'not available'])
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     MWT   4.61    484.0    65           n.a.
2    MSFT    NaN     85.0    64      billgates
3     RJL    NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [ ]:
# na_value use like distionary so we select column empty

df = pd.read_csv('stock_market_data.csv',header=1,na_values={
    'eps':['not available', -1],
    'revenue':[-1],
    'price':['n.a.'],
    'people':['n.a.']
})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     MWT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0      billgates
3     RJL    NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [ ]:
# to save csv and remove index
df.to_csv('no_index.csv',index=False)