##### Dataframe is a main object in pandas. it is used to represent data with rows and columns (tabular or excel spreadsheet like data)

In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('weather.csv')
df.head() # show the upper data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [9]:
df.tail() # show the lower

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [6]:
row , column = df.shape
row

6

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          6 non-null      object
 1   temperature  6 non-null      int64
 2   windspeed    6 non-null      int64
 3   event        6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [10]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [12]:
# indexing 

df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [ ]:
# reverse index
df[::-1]

        day  temperature  windspeed  event
5  1/6/2017           32          2  Sunny
4  1/5/2017           32          4   Rain
3  1/4/2017           24          7   Snow
2  1/3/2017           28          2   Snow
1  1/2/2017           35          7  Sunny
0  1/1/2017           32          6   Rain

In [14]:
# show the all columns
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [15]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [16]:
df.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [17]:
# show the multiple 
df[['day','event']]

        day  event
0  1/1/2017   Rain
1  1/2/2017  Sunny
2  1/3/2017   Snow
3  1/4/2017   Snow
4  1/5/2017   Rain
5  1/6/2017  Sunny

In [18]:
# check the column type
type(df['event'])

pandas.core.series.Series

In [19]:
df['temperature'].max()

np.int64(35)

In [ ]:
# coditionally check 
df[df.temperature > 30]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [21]:
df[df.temperature == df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [22]:
# statically check all datafarame
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.500000   4.666667
std       3.885872   2.338090
min      24.000000   2.000000
25%      29.000000   2.500000
50%      32.000000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [40]:
# set index "day" 
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           32          2  Sunny